### ISSUE TITLE
Conversion from String to CString ?

### ISSUE THREAD

**Issue by vsiles** [Amanieu/cstr_core#1]
Hi ! I'm looking for a crate that could help me deal with some embedded C code. My goal is to use String/str in my Rust code, and transform them into CString/CStr before calling external C code.

Is this possible with your crate ? I didn't saw anything about that in the doc.

(I'm new to Rust, maybe my idea is not possible at the moment)

Best,
V.

**Comment by Amanieu** [comment]
You should just be able to use `CString::new()` for this.
