### ISSUE TITLE
Make CStr::from_bytes_with_nul_unchecked a constant function

### ISSUE THREAD

**Issue by notgull** [Amanieu/cstr_core#14]
It would be nice if I were able to initialize CStr's in a constant context. [The standard library equivalent has this functionality](https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul_unchecked), and it doesn't seem like the implementation here is different from that. If there if interest, I am willing to implement a pull request for this feature.

**Comment by Amanieu** [comment]
I am happy to accept a PR for this!

**Comment by notgull** [comment]
A minor issue: const pointer dereferencing requires the `#![feature(const_raw_ptr_deref)]` feature gate. In order to get around this, I propose adding a new feature gate to `cstr_core`, to the tune of `const_unsafe_new`. When this feature is enabled; `from_bytes_with_nul_unchecked` will be `const`; otherwise, it will not be. Enabling this feature would require a nightly compiler. I would like to know if this is an acceptable API change.

**Comment by Amanieu** [comment]
That sounds good to me. Traditionally I've used the `"nightly"` feature name for things like this.
